@extends('app')
@section('title')
  E-Lawyers Online - You & the Law
@endsection
@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="card margin-bottom-20">
        <div class="card-body">
          <h2 class="margin-bottom-20">
            <strong>You & the Law</strong>
          </h2>
          <div style="padding:0 25px 25px 0;" class="float-left">
            <img src="{{ asset('img/everydaylaw_pic.jpg') }}" width="160" />
          </div>
          <h3 class="margin-bottom-20">Annulment of Marriage, in the Philippines!</h3>
          <p><em>ATTY.! Ayaw pumayag pumirma ng mister ko sa agreement para sa annulment ng kasal namin! Paano gagawin ko? </em></p>
          <p> This is a common misconception among Filipinos regarding the legal concept of marriage and annulment here in the Philippines. My answer is that you cannot do that here in the Philippines. We sometimes encounter or hear this discussion from our relatives, friends and acquaintance with troubled marriages giving the notion that it is allowed under Philippine law for the parties to simply agree on the &#8220;hiwalayan&#8221; or dissolution of their marriage. To state it again, this is not allowed under Philippine law.</p>
          <p>In the U.S.A., Japan and other countries, divorce is legal, where couples could marry in the morning and obtain a divorce decree in the afternoon. Remember Britney Spears marrying her childhood friend Jason Allen Alexander on January 3, 2004, at Las Vegas wherein the marriage lasted 55 hours and ended in annulment. Had Britney Spears been a Filipina, she would have difficulty unknotting her marriage ties because that kind of process of marriage and annulment is not allowed here. </p>
          <p>I would like to impart to our readers the underlying legal reasons why it is very hard to obtain an annulment decree here in the Philippines. </p>
          <p>Our supreme law, the 1987 Philippine Constitution, provides that it is the policy of our State <em>&#8220;to protect and strengthen the family as the basic autonomous social institution and marriage as the foundation of the family&#8221; (Section 12 of Article II and Sections 1 and 2 of Article XV)</em>. &#8220;Our family law is based on the policy that marriage is not a mere contract, but a social institution in which the state is vitally interested. The State can find no stronger anchor than on good, solid and happy families. The break up of families weakens our social and moral fabric and, hence, their preservation is not the concern alone of the family members. Thus, our Constitution devotes an entire Article on the Family, recognizing it &#8220;as the foundation of the nation&#8221;. <strong><em> It decrees marriage as legally &#8220;inviolable,&#8221; thereby protecting it from dissolution at the whim of the parties.</em></strong> Both the family and marriage are to be &#8220;protected&quot; by the state.&#8221; (Asqueta vs. Republic, G.R. No. 180668, May 26, 2009) </p>
          <p>In short, marriage as well as its dissolution cannot be left alone to the husbands and wives or to their children by the mere expedient act of signing a piece of paper agreeing for such dissolution, because the State, our Government always have the last and final say whether to grant the annulment or not. This is why the Office of Solicitor General (OSG) and the Public Prosecutors, as lawyers of the State, are required to participate and attend the annulment proceedings every step of the way.<br />
          </p>
          <p>While our 1987 Philippine Constitution protects the sanctity of marriage, our Family Code provides estranged couples a way to dissolve their marriage ties, by annulment of void and voidable marriages. </p>
          <p>The most popular and widely used ground for annulling a marriage is under Article 36 of the Family Code. This legal process is known as declaration of absolute nullity of marriage on the ground of psychological incapacity to fulfill the marital and/or parental obligations as embraced in Articles 68 up to 71 of the Family Code as regards the husband and wife as well as Articles 220, 221 and 225 as regards to their children. </p>
          <p>Many people call this process as &#8220;annulment&#8221; but in strict legal term, it is declaration of absolute nullity of marriage on the ground of psychological incapacity to comply with essential marital and parental obligations. On the other hand, annulment is the process of voiding a marriage due to under age, insanity, fraud, force or intimidation, physical incapacity to consummate the marriage or due to serious and incurable sexually transmitted disease (Article 45 of the Family Code). This is also very different from &#8220;legal separation&#8221; (Article 55 of the Family Code) wherein you will only be separated by bed and board with your spouse and the marriage ties will not be cut off. In short, one will remain as married to his/her spouse in &#8220;legal separation,&#8221; without any right to re-marry, whereas in the &#8220;declaration of nullity of marriage on the ground of psychological incapacity&#8221;, the marriage ties will be cut-off and both spouse are allowed by law to re-marry.</p>
          <p>However, &#8220;declaration of nullity of marriage on the ground of psychological incapacity&#8221; is easier said than done. Our Supreme Court consistently ruled that this psychological incapacity must be characterized by (a) gravity, (b) juridical antecedence, and (c) incurability [Santos vs. Court of Appeals, 310 Phil. 21 (1995)].</p>
          <p>The burden of proof to show the nullity of the marriage belongs to the person who filed the case. The wife cannot just say that she wanted her marriage annulled under Article 36 just because she caught her husband having an illicit affair. It is not simply as that because our courts strictly requires from the person filing the case to prove that the psychological incapacity must be medically or clinically identified, sufficiently proven by experts (psychologists/psychiatrists) and/or corroborated by relatives or friends intimately related. Irreconcilable differences, conflicting personalities, emotional immaturity and irresponsibility, physical abuse, habitual alcoholism, sexual infidelity or perversion, and abandonment, by themselves, also do not warrant a finding of psychological incapacity under the said Article (Republic of the Phils. vs. Iyoy, 470 SCRA, pp. 525-526).</p>
          <p>Also, the incapacity must be proven to exist at &#8220;the time of the celebration&#8221; of the marriage. The evidence must show that the illness was existing when the parties exchanged their &#8220;I do&#8217;s.&#8221; That is why psychological reports contains the childhood and adulthood background of the person concerned to determine if there is evidence showing that the incapacity is already existing prior to the marriage. Such incapacity must also be shown to be medically or clinically permanent or incurable. (Republic of the Philippines v. Court of Appeals and Molina, G.R. No. 108763, February 13, 1997, 268 SCRA 198 and companion cases)</p>
          <p>To prove that one is psychologically incapacitated to comply with essential marital and parental obligations, the person filing the case must be examined by a clinical psychologist/psychiatrist first wherein she/he will be tested and interviewed regarding personal and family history and psychological background. The other spouse will be notified and invited for interview and testing also but it is the usual case that such spouse will not appear. In the case of Marcos vs. Marcos [397 Phil. 840 (2000)], the Supreme Court relaxed the rules on the expert evidence when it ruled that &#8220;the totalities of the evidence presented are enough to sustain a finding of psychological incapacity, there is no need to resort to the actual medical examination of the person concerned.&#8221; &#8220;While such examination is desirable, we recognize that it may not be practical in all instances given the oftentimes estranged relations between the parties. For a determination though of a party’s complete personality profile, information coming from persons intimately related to him (such as the party's close relatives and friends) may be helpful.&#8221; (Suazo vs. Suazo, G.R. No. 164493, March 10, 2010)</p>
          <p>Thereafter, the psychologist will issue a psychological report as one of the evidence in court and the psychologist will testify regarding the same. Upon filing of the petition in court, the public prosecutor will be directed to investigate if there is collusion between the parties and a certification will be issued for that purpose. Trial of the case will thereafter proceed and the person who filed the case must also testify in court regarding the allegations in the petition and at least one or more witness to corroborate the allegations in the petition. After presentation of evidence and if no opposition was filed by the other spouse, the same will be submitted for decision. This is the procedure for the declaration of nullity of marriage under Article 36 and the release of the decision of the case usually takes time depending on the capacity of the handling judge to finish the review of the evidence of the case.</p>
          <p>With the strict state policy on marriage, coupled with the heavy burden on the petitioner to prove psychological incapacity and the tedious process of proving the same in court, it is no wonder that many Filipinos are having a hard time in their annulment cases.</p>
          <p>As our oldies always say, <em>“ang pagpapakasal ay hindi isang kanin na bigla na lang isusubo at iluluwa pag ikaw ay nainitan”.</em> This adage true in the past and remains true today because more and more Filipinos are having difficulties in obtaining annulment decrees and realizing that their marriage cannot just be simply annulled by signing an agreement with her spouse. This kind of thinking, or worse of preparing such an agreement mentioned above, will do more harm than good to the estranged couples, as the same will be a clear evidence of collusion or connivance between them which is abhorred by the State. This agreement by the estranged couples can be used as evidence of collusion and will be fatal to the annulment case as the public prosecutor will not issue a certificate of non-collusion to the parties and will be the court’s basis for the denial of the petition.</p>
          <p>I hope that this article will somewhat enlighten the readers regarding marriage and annulment process here in the Philippines. Every litigant must know his/her legal rights before filing case. To avoid legal pitfalls in the annulment of marriage, it is better to consult a lawyer first so that parties in the annulment case will be properly guided.</p>

        </div>
      </div>
      @include('ads.big')
    </div>
    <div class="col-md-4">
      @if (Auth::check())
        @include('auth.user-info-partial')
      @else
        @include('auth.login-partial')
      @endif
      @include('layouts.side-navigator')
    </div>
  </div>
</div>
@endsection
@section('script')
  <script type="text/javascript">
  </script>
@endsection