<h4 class="margin-top-20 margin-bottom-20">
  Online Legal Consultation By Office Conference
</h4>
<div>
  <p>If you wish to set a face-to-face meeting with the lawyer, this is possible through this service.  In our online form, choose your preferred date and time of the meeting. Don't forget to provide in advance the necessary facts/details, objectives and questions relevant to your legal concern. Our office is situated at Suite 10-G Strata 100 Condominium, 100 F. Ortigas Jr. Road, Ortigas Center, Pasig City, Metro Manila.  E-Lawyers Online will send the initial legal advice through e-mail based on the given information and during the conference the client can explore more on the chances or probability of winning his/her case by asking follow-up questions from the lawyer.</p>
  <p>(Kung gusto mo ng personal at harapang pagkonsulta sa abogado, pwede mo itong gawin sa serbisyong ito. Meron dito na kalendaryo na magagamit mo para pumili ng araw at oras ng office conference at online form upang ikaw ay makapagbigay ng mga kwento ng mga pangyayari ng iyong problemang legal at mga detalye nito, ang iyong hangarin o gustong mangyari at mga katanungan na may kinalaman sa iyong kaso o problemang legal at ang aming paunang payong legal ay ipapadala sa iyo sa pamamagitan ng email. Ang aming paunang payong legal ay iyong magagamit upang makapagtanong pang muli ng mas malalim na tanong at masagot ang mga ito sa oras ng office conference. An gaming office ay nasa Suite 10-G Strata 100 Condominium, 100 F. Ortigas Jr. Road, Ortigas Center, Pasig City, Metro Manila)</p>
  <p><strong>Fee:  PhP 2,000 per hour</strong></p>
  Tips:                          
  <ul>
  <li>It will be useful for the client to write the complete facts, objectives, and questions regarding his/her legal problem using any word processor program (like Microsoft Word, Wordpad, or Notepad) for an easy cut-and-paste process. (Kung mahaba ang kwento ng mga pangyayari ng problemang legal, mas makakabuti na ito ay i-type muna sa word processor program (like Microsoft Word, Wordpad, or Notepad) at mag cut-and-paste ng na-type na kwento)<br /> <br /></li>
  <li>For any documents, which can be valuable for the case, clients can upload any Microsoft Word, Portable Document Format (PDF), or a scanned image (in JPEG format) for a more comprehensive legal advice from E-Lawyers Online. (Kung meron kayong papel o dokumento na parte o makakatulong sa inyong kaso o problemang legal, pwede itong i-scan at i-attach dito para makapagbigay ang E-Lawyers Online ng mas kumpleto at malawak na payong legal.)<br /> <br /></li>
  <li>We advised you to be at our office 30 minutes before the set schedule of office conference for purposes of preparation of documents and initial interview. (Pinapayuhan kayo na dumating sa opisina namin ng maagap ng 30 minuto sa napagkasunduang oras para sa paghahanda ng mga dokumento at paunang interview o pakikipanayam.  Maghanda ng kopya ng kwento ng iyong problemang legal, paunang payong legal at listahan ng mga kasunod na katanungan base dito sa oras ng office conference.)</li>
  </ul>
</div>