<h4 class="margin-top-10 margin-bottom-20">
  Online Legal Consultation By Video Conference
</h4>
<div>
  <p>Some people are not contented with just an email exchange.  You can set up a video conference call or chat using Skype or Yahoo Messenger when you avail this service.  There's an online form for you to fill up and select a preferred date and time for the video conference call or chat. You also need to indicate the necessary facts/details, objectives and questions that you want to ask about. E-Lawyers Online will send the initial legal advice via email.  You and the lawyer can discuss in depth during the video conference call.</p>
  <p>(Ang ibang tao ay hindi kuntento sa payong legal na pagpapalitan lang ng email. Kung kaya kami ay merong serbisyo na video conference call gamit ang Skype o Yahoo Messenger.  Meron dito na kalendaryo na magagamit mo para pumili ng araw at oras ng video conference at online form upang ikaw ay makapagbigay ng mga kwento ng mga pangyayari ng iyong problemang legal at mga detalye nito, ang iyong hangarin o gustong mangyari at mga katanungan na may kinalaman sa iyong kaso o problemang legal at ang aming paunang payong legal ay ipapadala sa iyo sa pamamagitan ng email. Ang aming paunang payong legal ay iyong magagamit upang makapagtanong pang muli ng mas malalim na tanong at masagot ang mga ito sa oras ng video conference call)</p>
  <p><strong>Fee:  PhP 2,000 per hour</strong></p>
  Tips:                          
  <ul>
  <li>It will be useful for the client to write the complete facts, objectives, and questions regarding his/her legal problem using any word processor program (like Microsoft Word, Wordpad, or Notepad) for an easy cut-and-paste process. (Kung mahaba ang kwento ng mga pangyayari ng problemang legal, mas makakabuti na ito ay i-type muna sa word processor program (like Microsoft Word, Wordpad, or Notepad) at mag cut-and-paste ng natype na kwento) <br /> <br /></li>
  <li>For any documents, which can be valuable for the case, clients can upload any Microsoft Word, Portable Document Format (PDF), or a scanned image (in JPEG format) for a more comprehensive legal advice from E-Lawyers Online. (Kung meron kayong papel o dokumento na parte o makakatulong sa inyong kaso o problemang legal, pwede itong i-scan at i-attach dito para makapagbigay ang E-Lawyers Online ng mas kumpleto at malawak na payong legal.) <br /> <br /></li>
  <li>Make sure you have the following: built-in or separate headset with microphone and webcam. Before the video conference, test if your headset, microphone, and webcam are working properly. Prepare a copy of the facts and details for reference during the conference. (Siguraduhin na meron kang microphone, headset at webcam. Bago ang oras ng video conference, subukan muna ang microphone, headset at webcam kung ito ay gumagana ng maayos. Maghanda ng kopya ng kwento ng iyong problemang legal, paunang paying legal at listahan ng mga kasunod na katanungan base dito sa oras ng video conference.)</li>
  </ul>
</div>